[ADD] 유저 회원가입 엔드포인트
wecode-bootcamp-korea/36-backend-westagram pull request #10
Opened 2022-08-02 03:45 UTC by Mjj4682

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 실패시 에러 반환
- 가입시 201 userCreated 반환
- 조회시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-03 08:02 UTC, kyeongraekim requested changes

2022-08-03 08:02 UTC, kyeongraekim commented on teamB/JungJin/app.js
> +    const query = myDataSource.query(`SELECT * FROM users`, (err, rows) => {
웹서비스 Github 에 올라오는 코드들은 제 3자의 개발자들도 직관적으로 파악할 수 있어야 합니다. 

select 문에서의 asterisk의 사용을 지양해주시고 아래와 같이  안에서 어떠한 항목을 끌어오는지 파악할 수 있게 변경해주세요~

```javascript
app.post("/users/sign-up", async (request, response) => {
	const { name, email, profile_image, password } = request.body
    
	await database.query(`
        INSERT INTO users (
            name, 
            email, 
            profile_image, 
            password
        ) VALUES (
            ?, 
            ?, 
            ?, 
            ?
        )`, [ name, email, profile_image, password ]
	); 
    response.status(201).json({ message : "successfully created" });
});

2022-08-03 08:02 UTC, kyeongraekim commented on teamB/JungJin/app.js
> +    const query = myDataSource.query(`SELECT * FROM users`, (err, rows) => {
그리고 해당 get 함수는 어떠한 내용을 의도한 것인지 코멘트로 의도를 남겨주실 수 있으실까요?
혹시 로그인을 의도하신 것이라면, 로그인에 필요한 http 메소드가 get 인지 post인지 한 번 고민해보세요
그리고 과제 미션으로는 로그인을 일부러 생략해두었습니다. 다음주에 듣게될 authentication 세션에서 본격적으로 도입할 예정이기 때문이지요!

2022-08-03 08:02 UTC, kyeongraekim commented on teamB/JungJin/app.js
> +    const sql = {name:name, email:email, profile_image:profile_image, password:password}
해당 내용도 코드의 확장성과 가독성 상승을 위해 line breaking을 해서 각 데이터 요소를 한눈에 볼 수 있게 관리해주세요~

2022-08-03 08:06 UTC, Mjj4682 commented on teamB/JungJin/app.js
> +    const query = myDataSource.query(`SELECT * FROM users`, (err, rows) => {
아 get은 그냥 유저 목록 확인하려고 넣었습니다!

2022-08-04 01:33 UTC, lordmyshepherd requested changes

2022-08-04 01:33 UTC, lordmyshepherd commented on teamB/JungJin/app.js
> +    const query = myDataSource.query(`INSERT INTO users set ?`, sql)
```jsx
// Example

INSERT INTO table (a, b, c) VALUES (1,2,3)
INSERT INTO table SET a=1, b=2, c=3
```

- 위 예제에서 보시는 것과 같이 MySQL에서는 VALUES 혹은 SET을 사용해서 데이터를 추가할 수 있습니다. 두 문장의 성능 차이는 없고 동일하게 동작합니다. 하지만 VALUES는 SQL의 표준이고 SET은 MySQL에서 제공하는 확장된 기능입니다.
- 그러므로 모든 RDBMS에서 표준으로 사용하고 있는 VALUES를 사용해서 코드를 작성하는 것이, 나중에 사용하는 데이터베이스가 mysql에서 다른 데이터베이스로 변경되더라도 변화에 쉽게 대응할 수 있는 구조가 될 수 있습니다.

2022-08-04 02:58 UTC, lordmyshepherd approved these changes

2022-08-04 02:58 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-08-04 02:58 UTC, merged