[이지현 - teamA] Assignment : Project Layered pattern 적용
wecode-bootcamp-korea/36-backend-westagram pull request #101
Opened 2022-08-08 12:58 UTC by LeeJ1Hyun

## 수정 사항 간략한 한줄 요약
- Layered pattern 적용
		 
## 수정 사항들 자세한 내용
- controllers > postController.js, userController.js | request와 response에 대한 처리 역할
- middlewares > | 거쳐갈 미들웨어들의 모음 역할
- models > postDao.js, userDao.js | 데이터베이스와의 통신 역할
- routes > index.js, postRouter.js, userRouter.js | endpoint를 분리해서 해당 endpoint에 집중, endpoint와 controller를 연결
- service > postService.js, userService.js | 비즈니스 로직을 담당한 후, model layer를 호출, controller layer로 결과를 반환
- utils > | 자주 사용하는 모듈들, 상수들 모아두는 역할
- app.js | 단독 서버 역할

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-09 02:20 UTC, lordmyshepherd requested changes

2022-08-09 02:20 UTC, lordmyshepherd commented on teamA/jihyun/models/postDao.js
> +  });
dataSource 관련된 코드들이 모든 dao 마다 존재합니다.
이렇게 되면 매번 dataSource를 만들고 initialize 하기 때문에, 아래와 같이 models/dataSource.js 파일을 만든 후에 dataSource를 만들고 initialize()하는 코드를 옮겨주세요.

```javascript
//models/dataSource.js

const myDataSource = new DataSource({
    type: process.env.TYPEORM_CONNECTION,
    host: process.env.TYPEORM_HOST,
    port: process.env.TYPEORM_PORT,
    username: process.env.TYPEORM_USERNAME,
    password: process.env.TYPEORM_PASSWORD,
    database: process.env.TYPEORM_DATABASE
});

myDataSource.initialize()
.then(() => {
    console.log("Data source has been initialized!");
})
.catch((err) => {
    console.error("Error during Data Source initialization", err);
    myDataSource.destroy();
});
```

2022-08-10 01:05 UTC, LeeJ1Hyun commented on teamA/jihyun/models/postDao.js
> +  });
확인한 후 반영했습니다. 리뷰 감사합니다.

2022-08-10 02:07 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-08-10 02:07 UTC, merged