[정재하- teamA] Assignment : Project Layered Pattern 적용
wecode-bootcamp-korea/36-backend-westagram pull request #104
Opened 2022-08-09 06:09 UTC by JeongJaeHa

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- CRUD API에 Layered Pattern 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- app.js 에 모든 코드를 넣어 동작하였던 방식을 Router, Controller, Services, Dao 로 구분하여 동작할수 있도록 수정
- 실패시 에러 반환
- 성공시 해당 상황에 맞는 결과값 또는 메세지 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-09 06:50 UTC, lordmyshepherd requested changes

2022-08-09 06:50 UTC, lordmyshepherd commented on teamA/jeongjaeha/models/postDao.js
> +const { Database, initialize } = require("./Database.js");
재하님! initialize를 import 하시는 이유가 있으신가요?

2022-08-09 06:50 UTC, lordmyshepherd commented on teamA/jeongjaeha/models/postDao.js
> +      `,
indentation이 잘 맞지 않는 것 같습니다!

2022-08-09 06:50 UTC, lordmyshepherd commented on teamA/jeongjaeha/services/postServices.js
> +const postLikeDao = require('../models/postDao')
아래에서 post와 관련된 Dao가 postDao, viewAllDao, ... 등 많이 있습니다.
이를 하나로 통합해서 관리해야 Layered Pattern의 의미가 있습니다.

아래와 같은 구조가 될 수 있도록 수정부탁드립니다~

```suggestion
const postDao = require('../models/postDao)

postDao.create()
postDao.update()
postDao.delete()
postDao.bulk_insert()

```

2022-08-10 01:25 UTC, JeongJaeHa commented on teamA/jeongjaeha/models/postDao.js
> +const { Database, initialize } = require("./Database.js");
Database.js 에서 export해서 별 생각없이 import 하였는데 생각보니 export, import 할 이유가 없는것 같습니다.

2022-08-10 01:30 UTC, JeongJaeHa commented on teamA/jeongjaeha/services/postServices.js
> +const postLikeDao = require('../models/postDao')
수정하였습니다.

2022-08-10 01:32 UTC, JeongJaeHa commented on teamA/jeongjaeha/models/postDao.js
> +      `,
vsc 화면에서 볼때는 괜찮은데 리포지토리에 업로드하면 좀  안맞는 거 같습니다.
혹시 Tip같은게 있을까요?

![image](https://user-images.githubusercontent.com/99805929/183790783-be9ed71c-78e2-4958-82af-6ba3824a3151.png)

2022-08-10 02:09 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-08-10 02:09 UTC, merged