[ADD] signup, signin password 암호화 by bcrypt
wecode-bootcamp-korea/36-backend-westagram pull request #115
Opened 2022-08-10 12:13 UTC by LeeJ1Hyun

## 수정 사항 간략한 한줄 요약
- signup, signin password 암호화 by bcrypt

![로그인 API 통신 후 성공 결과](https://user-images.githubusercontent.com/100523786/183898047-845f3b4e-eea4-4371-8196-89616080f077.png)
로그인 API 통신 후 성공 결과

![로그인 API 통신 후 error 결과](https://user-images.githubusercontent.com/100523786/183898103-180a696e-ff6c-472a-838c-1c153b88f531.png)
로그인 API 통신 후 실패 결과

![user_Pwd_bcrypt](https://user-images.githubusercontent.com/100523786/183898172-2e59d7f0-185d-4d64-9454-08d683332d0b.png)
사용자 비밀번호 암호화 DB 저장 결과
		 
## 수정 사항들 자세한 내용
- userController.js > signUp, signIn 암호화, 복호화 추가
- 실패시 400 상태코드와 에러메세지 message: "Invalid User" 반환
- 성공시 200 상태코드와 accessToken 반환

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-12 09:19 UTC, kyeongraekim requested changes

2022-08-12 09:19 UTC, kyeongraekim commented on teamA/jihyun/middlewares/auth.js
> +    const accessToken = headers.split(" ")[1];
- 해당 부분은 혹시 아래 예시로는 정상 작동을 안했는지가 궁금하네요!

2022-08-12 09:19 UTC, kyeongraekim commented on teamA/jihyun/middlewares/auth.js
> +    const accessToken = headers.split(" ")[1];
``` javascript
const accessToken = req.headers("authorization")

2022-08-12 09:19 UTC, kyeongraekim commented on teamA/jihyun/middlewares/auth.js
> +      });
- 현재 불필요한 if else 로직의 중첩이 이루어 지고 있는 것 같네요! 해당 내용을 한 번 수정해보세요!
- 그리고 auth.js는 해당 토큰의 인가처리를 함과 동시에 다음 모듈로 해당 정보를 전달해야하는 목적이 있습니다. 다음의 유사한 사례를 참고하여서 한 번 수정해보세요!

```javascript

// 예시 (1)
const validateToken = async (req, res, next) => {
  try {
    const access_token = req.header('access_token');
    const decoded = jwt.verify(access_token, process.env.SECRET_KEY);
    const userId = decoded.id;
    const foundUser = await getUserById(userId);

    if (!foundUser)
      errorGenerator({ statusCode: 404, message: 'USER_NOT_FOUND' });
    req.userId = userId;
    next();
  } catch (err) {
    next(err);
  }
};



// (2) 예시

const jwt = require("jsonwebtoken");

const config = process.env;

const verifyToken = (req, res, next) => {
  const token =
    req.body.token || req.query.token || req.headers["x-access-token"];

  if (!token) {
    return res.status(403).send("A token is required for authentication");
  }
  try {
    const decoded = jwt.verify(token, config.TOKEN_KEY);
    req.user = decoded;
  } catch (err) {
    return res.status(401).send("Invalid Token");
  }
  return next();
};

module.exports = verifyToken;

2022-08-12 09:19 UTC, kyeongraekim commented on teamA/jihyun/models/userDao.js
> +// 암호화된 비번
코드 진행에 있어서 독해로 충분히 이해가능한 불필요한 주석은 삭제해주셔도 무방합니다!

2022-08-12 09:19 UTC, kyeongraekim commented on teamA/jihyun/models/userDao.js
> +		 users.password
indentation 한 번 다시 신경써주세요!~

2022-08-13 10:02 UTC, LeeJ1Hyun commented on teamA/jihyun/middlewares/auth.js
> +    const accessToken = headers.split(" ")[1];
jwt를 받는 방식에 대해 구글링 하다, Front-end에서 jwt를 headers에 담아 보낼 때 토큰 앞에 Bearer이라는 타입을 붙여 보내는 것이 표준적인 방법이라고 하여 위와 같은 코드를 작성하게 되었습니다.

![Bearer_jwt](https://user-images.githubusercontent.com/100523786/184478819-e5d31158-39e0-4be7-9fff-996bb30a367e.png)

실제로 Postman으로 테스트를 해볼 때도 앞에 Bearer을 붙이고 한칸 띄우고 jwt를 전송하였기 때문에 해당 문자열을 공백을 기준으로 split으로 자르고 배열에 담긴 것중 첫번째 index의 요소(jwt)를 가져와 accessToken이라는 변수에 할당하였습니다.

![authoriazation_코드_이유](https://user-images.githubusercontent.com/100523786/184478872-951f8663-c2a6-4c15-b9f0-6b8c382c27d8.png)

jwt를 headers라는 객체에 담아 key : value 형태로 가져오기 때문에 dot(.)으로 접근하거나, 대괄호([ ])로 접근해야 하므로 괄호 형태로는 가져올 수 없다고 생각합니다. 잘못 알고 있는 점이 있다면 알려주시면 감사하겠습니다. 세심한 리뷰 감사합니다!

2022-08-13 10:04 UTC, LeeJ1Hyun commented on teamA/jihyun/models/userDao.js
> +// 암호화된 비번
자꾸 헷갈려 주석을 달아놨다가 지우는 걸 잊어버렸습니다. 반영했습니다!

2022-08-13 10:08 UTC, LeeJ1Hyun commented on teamA/jihyun/models/userDao.js
> +		 users.password
들여쓰기 같은 기본적인 항목들 다시 한번 점검하고 push하도록 하겠습니다. 감사합니다!

2022-08-13 10:50 UTC, LeeJ1Hyun commented on teamA/jihyun/middlewares/auth.js
> +      });
남겨주신 코드와 기존 제 코드를 비교해보고 각 부분에서 선택적으로 가져와 다시 작성하여 push하였습니다. 수정 후 POST도 잘 작동되는 것을 확인했습니다.

![tokenValid 수정 후 DB 결과](https://user-images.githubusercontent.com/100523786/184480375-ce81688b-44a7-44df-b0bc-a35da5ac8175.png)

2022-09-26 09:28 UTC, closed without merging