[박근우-teamA] Layered architecture와 Error Handling 적용
wecode-bootcamp-korea/36-backend-westagram pull request #118
Opened 2022-08-11 01:54 UTC by parklaus1078

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 원래 Monolithic architecture였던 app.js 파일을 MSA(MicroServiceArchitecture)로 변환
- Error handling 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 필요한 입력값이 입력되지 않았다면 Error code: 400과 KEY_ERROR라는 메세지를 출력
- 각 입력값들의 타입이 의도한 바와 다르다면 Error code: 409와 INVALID INPUTS/INVALID_IDs라는 메세지를 출력
- 그 이외 쿼리문에서 에러가 생긴다면 Error code: 500과 INVALID_DATA_INPUTS 메세지를 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-11 07:02 UTC, kyeongraekim requested changes

2022-08-11 07:02 UTC, kyeongraekim commented on teamA/GeunWoo/controllers/postController.js
> +        return res.status(201).json(getPostings);
데이터 조회 목적의 요청에 대한 응답 인 것 같아 보여집니다 이에 적절한 http 상태코드를 다시 한 번 고민해보세요!

2022-08-11 07:02 UTC, kyeongraekim commented on teamA/GeunWoo/controllers/postController.js
> +    postPostings, getPostings, getPostingsByUserId, updatePostings, deletePostings
- 추후 추가 모듈들이 들어올 수 있는 확장성과 제 3의 개발자들의 가독성을 고려해서 해당 내용에 대한 line breaking이 이루어지면 좋을 것 같네요!~

2022-08-11 07:02 UTC, kyeongraekim commented on teamA/GeunWoo/routes/likeRouter.js
> +router.post('/createLikes', likeController.createLikes);
- 해당 내용은 오늘 오전에 전달해드린 RESTful 한 엔드포인트 설계법에 맞게 적절히 수정해보세요!~

2022-08-11 07:02 UTC, kyeongraekim commented on teamA/GeunWoo/routes/postRouter.js
> +router.delete('/deletePostings/:post_id', postController.deletePostings);
- 이 부분들도 오늘 오전에 전달해드린 RESTful 한 엔드포인트 설계법에 맞게 적절히 수정해보세요!~

2022-08-11 07:02 UTC, kyeongraekim commented on teamA/GeunWoo/services/likeService.js
> +    }
- 서비스 단에서의 좋아요와 관련하여서 숫자가 올바르게 들어왔는지에 대한 에러는 컨트롤러 단에서 키에러와 함께 잡아줄 수 있어 보이네요.
- 서비스적인 의미에서는 해당 좋아요에 대한 중복 체크를 막는 예외처리를 오히려 추가해주는 것이 그 의미론적 접근시 더 옳다고 생각합니다.

2022-08-11 09:37 UTC, kyeongraekim commented on teamA/GeunWoo/services/likeService.js
> +    }
- Like에 대한 unique constraint이 db 스키마 선에서 적용되어 있음이 확인되네요! 해당 내용은 한 기업의 비즈니스 로직 선(서비스선)에서 db단에 흘러들어가기전에 예외처리를 해야되는 부분이라고 생각이 듭니다.
- Controller로 옮긴 것은 잘해주셨으나 .. 동일한 유저가 동일한 post에 좋아요 버튼을 할 수 없게끔 에러 처리를 한 번 다시 도전해 보세요!

2022-08-11 10:25 UTC, parklaus1078 commented on teamA/GeunWoo/services/likeService.js
> +    }
아하 그럼 서비스에서 유니크한지 아닌지를 걸러낼 수 있는 if문이 필요하겠군요?

2022-08-12 05:13 UTC, kyeongraekim approved these changes
LGTM!~ 이제 로그인 인증/인가를 bcrypt와 jwt를 이용하여서 접목시켜보세요!~

2022-08-12 05:13 UTC, merged