[정세한 - teamA] Assignment : 인증 & 인가 적용+ ErrorHandling
wecode-bootcamp-korea/36-backend-westagram pull request #127
Opened 2022-08-12 08:20 UTC by jungsae

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 각 레이어별 에러 핸들링
- 인증/인가
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-12 09:58 UTC, kyeongraekim requested changes

2022-08-12 09:58 UTC, kyeongraekim commented on teamA/saehan/controllers/postController.js
> +        const token = req.headers.authorization;
- 받아들인 token속 유저정보가 내 디비안에 존재하는 유저인지를 확인하는, 즉 인가 과정을 확인해보는 auth.js 파일을 별도의 미들웨어 모듈로 만들어보세요.

2022-08-12 09:58 UTC, kyeongraekim commented on teamA/saehan/models/postDao.js
> +            p.id AS Post_ID,
- 혹시 대문자로 작성한 이유가 따로 있으실까요? camel case 와 snake case의 불필요한 혼용처럼 보여집니다

2022-08-12 09:58 UTC, kyeongraekim commented on teamA/saehan/models/userDao.js
> +const emailDuplicate = async (email) => {
- 변수명이 다소 모호해보입니다. checkEmailDuplicacy 처럼 내가 의도한 모듈이 정확히 동작하고자 하는 내용을 변수명에 담아서 제 3의 개발자들의 가독성을 높여주세요.

2022-08-13 11:16 UTC, jungsae commented on teamA/saehan/models/postDao.js
> +            p.id AS Post_ID,
혼자 리턴 결과 조회해 볼 때 편하게 보려고 수정했었는데 원래대로 돌려놓지 않았던 거 같습니다. 수정하겠습니다.

2022-08-13 11:22 UTC, jungsae commented on teamA/saehan/models/userDao.js
> +const emailDuplicate = async (email) => {
넵

2022-08-22 10:35 UTC, closed without merging