Feature/post user endpoint
wecode-bootcamp-korea/36-backend-westagram pull request #21
Opened 2022-08-02 05:53 UTC by yenicall114

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 엔드포인트 구현했습니다.
<img width="1559" alt="user created" src="https://user-images.githubusercontent.com/104622110/182301666-8e4f9b11-491d-463f-bf13-ab237becfba7.png">

		

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-02 11:39 UTC, LeeJ1Hyun commented
LGTM!

2022-08-03 08:13 UTC, kyeongraekim requested changes

2022-08-03 08:13 UTC, kyeongraekim commented on teamB/YaeRin/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
해당 schema.sql 파일은 깃헙에 올라오면 안됩니다. 개인마다 로컬환경에서 생성된 스키마 세부내역이 다를 수 있었기 때문입니다. 깃 캐쉬삭제후 재푸시해주세요!

2022-08-03 08:13 UTC, kyeongraekim commented on teamB/YaeRin/app.js
> +app.post("/users", async (req, res) => {
뒤 endpoint 에 회원가입임을 기능의 API 엔드포인트를 의미하는 sign-up 정도를 추가해서 넣어주세요~ /users/sign-up

2022-08-03 08:13 UTC, kyeongraekim commented on teamB/YaeRin/db/migrations/20220802034509_create_users_posts_table.sql
> +CREATE TABLE users_posts (
해당 부분을 다대다 로 표현하신 이유가 따로 있으실까요? 
한 명의 유저가 여러개의 게시글을 달 순 있지만, 한 명의 게시글을 여러명의 유저가 기여할 수는 없을 것 같은데 혹시 고민해주신 부분이 있으시면 아래에 댓글로 작성해주세요!~

2022-08-03 08:27 UTC, yenicall114 commented on teamB/YaeRin/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
넵!

2022-08-03 09:12 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +app.post("/users", async (req, res) => {
넵!

2022-08-04 02:10 UTC, lordmyshepherd requested changes

2022-08-04 02:10 UTC, lordmyshepherd commented on teamB/YaeRin/package.json
> +{
- 이미 merge 했던 코드가 계속해서 올라올 경우에는 아래 절차를 통해서 해당 branch에 merge된 커밋 내역을 병합해주세요.
    
    ```bash
    git checkout main
    git pull origin main
    git checkout feature/branch
    git merge main // 만약에 이 상황에서 컨플릭트가 발생한다면, 해결합니다.
    
    // 모든 작업이 완료되면
    git push originm feature/branch 명령으로 다시 origin에 결과물을 push 합니다.
    ```

2022-08-04 02:10 UTC, lordmyshepherd commented on teamB/YaeRin/package.json
> +  "dependencies": {
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 “dependencies”에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 “devDependencies”에 포함되어서 production 레벨에서는 사용하지 않도록 만들어야 합니다.

2022-08-04 02:10 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +});
변수 선언부와 함수 호출부 사이에 한 줄씩 띄워서 가독성을 높여주세요.

```suggestion
  const { name, age } = req.body;
  
  await myDataSource.query(
    `INSERT INTO users(
      name, 
      age
      ) VALUES (?, ?);
      `,
    [name, age]
  );
  
  res.status(201).json({ message: "New User Created!" });

});
```

2022-08-04 02:10 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +  await myDataSource.query(
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```javascript
    await database.query(`
          INSERT INTO users (
              name, 
              email, 
              profile_image, 
              password
          ) VALUES (?, ?, ?, ?)`, 
          [ name, email, profile_image, password ]
    );
    ```

2022-08-04 07:26 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-04 07:26 UTC, merged