[백민석 Team-B] Assignment1 : Express APi 초기환경 세팅
wecode-bootcamp-korea/36-backend-westagram pull request #37
Opened 2022-08-02 16:26 UTC by sk8ilar

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
Express 설치 / 적용
nodemon 설치/ 적용
cors 설치 / 적용
dotenv 설치 /적용
morgan 설치 /적용
TypeORM 설치 / 적용
dbConnection 정상 작동 확인 

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
마지막 영상 보고있다가 1번과제는 당장 할 수 있겠구나 생각해서 중간에 멈췄습니다.
http 통신 잘 연결되는지 확인했고 진도 상으로 create a book post로 받는 것 까지 진행했습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
git에 branch 만들고 git add 하기전에 git init을 사용하는데 완전 엉켜서 다시했습니다,
혹시 git init은 구체적으로 어떤 상황에서 사용하나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-03 01:58 UTC, kyeongraekim requested changes

2022-08-03 01:58 UTC, kyeongraekim commented on teamB/minseok/.gitignore
> +node_modules/
db 폴더내에 migrations 폴더는 깃헙에 올려서 다른 개발자들과 함께 확인하며 관리해야하는 목적이 있습니다. 다만 스키마 파일은 개별 로컬 환경에 따라 내부 상세 내용들이 언제든 변경될 수 있으니 아래의 내용을 초기환경 세팅시 사전에 추가해주세요!~ // 추가로 vscode와 관련된 내용이 함께 나도 모르는 사이에 올라가지 않게 추가 설정을 해주세요!~

```
db/schema.sql
.vscode

2022-08-03 01:58 UTC, kyeongraekim commented on teamB/minseok/app.js
> +app.post('/books', async (req, res) => {
초기 환경 세팅과는 다른 내용이 올라와 있는데 해당 내용을 삭제하고 재푸시해주세요!~ 깃헙에 익숙해지기 위한 작업으로 생각해주시고 푸시하실 때 깃의 명령어 순서를 꼼꼼이 살펴보신 후 푸시해주세요!~

2022-08-03 01:58 UTC, kyeongraekim commented on teamB/minseok/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
해당 내용을 깃헙에 올라오지 않도록 설정해주시고 다시 푸시해주세요!~

2022-08-03 08:17 UTC, kyeongraekim requested changes
현재 세션 동영상 시연 예시인 책-작가 migration이 잘못 올라와있습니다. Westagram에 맞는 migrations을 다시 올려주세요~

2022-08-03 10:48 UTC, sk8ilar commented on teamB/minseok/.gitignore
> +node_modules/
수정 내용 완료했습니다.

2022-08-04 02:13 UTC, sk8ilar commented
그 책-작가 migration 내용을 삭제하고 기본 세팅만 다시 올렸는데 연결이 안된건가요? 혹시 어떤 부분이 문제인지 알려주실 수  있나요!!!

2022-08-04 06:03 UTC, sk8ilar commented
초기환경 세팅과 관련없는 것 다 삭제했습니다!! 확인 부탁드립니다.

2022-08-04 08:29 UTC, sk8ilar commented
진짜 진짜 마지막으로 다 바꿨습니다 확인 한번만 부탁드립니다!

2022-08-04 11:10 UTC, closed without merging