[이상우-teamB] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #84
Opened 2022-08-04 11:20 UTC by S-W-L

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Express API CRUD 전체 기능 구현
		 
## 수정 사항들 자세한 내용
- Express API CRUD 전체 기능
## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 02:09 UTC, lordmyshepherd requested changes

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +});
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +        u.id = p.user_id
- Alias를 사용하실 때에는 통일해서 사용해주세요.
- JOIN문은 한 줄로 작성해주세요~
```suggestion
        INNER JOIN posts AS p ON u.id = p.user_id
```

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +app.get("/posts", async (req, res) => {
마찬가지로 비동기 처리 코드를 수정해주세요.

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +app.get("/posts/:userId", async (req, res) => {
마찬가지로 비동기 처리 코드를 수정해주세요. callback은 계속해서 nested 되는 구조이기 때문에 코드의 가독성이 안좋아질 수 밖에 없습니다.

async/await 방식으로 수정해주세요~

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +    const {postId} = req.params;
params도 구조분해 할당을 통해서 한 줄로 줄여주세요~
```suggestion
    const { userId, postId } = req.params;
```

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +});
여기도 마찬가지로 비동기 처리 코드를 수정해주세요. callback은 계속해서 nested 되는 구조이기 때문에 코드의 가독성이 안좋아질 수 밖에 없습니다.

async/await 방식으로 수정해주세요~

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +    await myDataSource.query(
코드 전체적으로 DataSource.query와 DataSource.manage.query() 항식을 혼용해서 사용하고 있습니다.
DataSource.query()로 통일해주세요!

2022-08-05 02:09 UTC, lordmyshepherd commented on teamB/sangwoo/app.js
> +
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-08 01:39 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-08 01:39 UTC, merged

2022-08-08 01:40 UTC, kyeongraekim requested changes

2022-08-08 01:40 UTC, kyeongraekim commented on teamB/sangwoo/db/migrations/20220805044402_create_unique_table.sql
> +ALTER TABLE likes ADD UNIQUE INDEX (user_id, post_id)
이곳은 중복의 좋아요를 막는 기능인 것 처럼 보아, Unique Index가 아닌 Unique Constraint가 들어가야 할 것 같네요. 해당 내용에 대한 차이점을 한 번 고민해보세요!

2022-08-08 04:03 UTC, S-W-L commented on teamB/sangwoo/db/migrations/20220805044402_create_unique_table.sql
> +ALTER TABLE likes ADD UNIQUE INDEX (user_id, post_id)
Index 사용시 Unique Index의 대상이 되는 컬럼(user_id)이 중복을 허용하지 않아 한명의 유저가 다른 게시글 좋아요를 하지 못하는것 확인 했습니다. Constraint로 변경하여 모든 열의 값이 서로 다른지 확인하여 한명의 유저가 모든 게시글을 좋아요 누를 수 있게 변경하였습니다. 다만 현재 머지가 되어 새로운 브런치를 만들어야해서 추후 Layered Pattern 브런치에 수정내용 포함해서 푸쉬하겠습니다.