[류예린-teamB] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #85
Opened 2022-08-04 12:11 UTC by yenicall114

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Express API CRUD 전체 기능 구현했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 02:27 UTC, lordmyshepherd requested changes

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +});
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +// LIKE
이미 147 line의 코드에서 /like로 해당 엔드포인트가 LIKE 관련된 코드라는 것을 알 수 있기 때문에 주석은 지워주세요.

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +// LIKE
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +// DELETE post
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +// PATCH post
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +  );
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +});
여기도 위에서 드린 피드백과 마찬가지입니다.

callback 방식은 계속해서 nested되는 구조이기 때문에, 가독성에 좋지 않습니다.
async/await 방식으로 수정해주세요.

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +    WHERE u.id=p.user_id`,
복수의 테이블을 내부결합할 때에는 CROSS JOIN을 사용하는 것 보다는 INNER JOIN 키워드를 사용한 결합방법이 일반적으로 통용됩니다. INNER JOIN 방식으로 수정해주세요.

2022-08-05 02:27 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +app.patch("/posts", async (req, res) => {
과제 요구사항에 맞게 값은 업데이트 한 후에, 아래와 같이 업데이트된 값을 반환해주도록 코드를 수정해주세요.
```json
{
    "data" : {
        "userId"           : 1,
	"userName"         : "weCode"
        "postingId"        : 1,
        "postingTitle"     : "간단한 HTTP API 개발 시작!",
	"postingContent"   : "기존과 다르게 수정한 내용입니다."
    }
}
```

2022-08-05 02:36 UTC, lordmyshepherd requested changes

2022-08-05 02:36 UTC, lordmyshepherd commented on teamB/YaeRin/app.js
> +    [title, description, postId]
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
      UPDATE posts
      SET title = ?,
        description = ?
      WHERE id = ?`,
      [title, description, postId]
    );
    ```

2022-08-05 07:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +});
넵!

2022-08-05 07:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +// LIKE
넵!

2022-08-05 07:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +// DELETE post
넵!

2022-08-05 07:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +// PATCH post
넵!

2022-08-05 07:19 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +  );
넵!

2022-08-05 07:42 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +});
넵!

2022-08-05 07:48 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +    WHERE u.id=p.user_id`,
넵!

2022-08-05 11:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +app.patch("/posts", async (req, res) => {
넵!

2022-08-05 11:13 UTC, yenicall114 commented on teamB/YaeRin/app.js
> +    [title, description, postId]
넵!!

2022-08-08 01:41 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-08 01:41 UTC, merged