[이석원-teamB] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #87
Opened 2022-08-04 12:47 UTC by sockwon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 개발 환경 구축
- 사용자 회원가입 엔드포인트 구현
- 사용자 작성 게시글 검색 엔드포인트 구현
- 사용자 게시글 작성 엔드포인트 구현
- 사용자 게시글 삭제 엔드포인트 구현
- 사용자 게시글 수정 엔드포인트 구현
- 전체 게시글 검색 엔드포인트 구현
- 사용자 좋아요 엔드포인트 구현

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 첫 통합 pull request. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 멘토님들 고생이 많으십니다. 화이팅!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 03:02 UTC, lordmyshepherd requested changes

2022-08-05 03:02 UTC, lordmyshepherd commented on teamB/sockwon/app.js
> +    );
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-08-05 03:02 UTC, lordmyshepherd commented on teamB/sockwon/app.js
> +        res.status(201).json({MESSAGE : 'success!'})
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
      UPDATE posts
      SET title = ..,
        description = ..
      WHERE id = ..`,
    );
    ```

2022-08-05 03:02 UTC, lordmyshepherd commented on teamB/sockwon/app.js
> +    await appDataSource.query(
위에서 드린 피드백과 마찬가지로 callback 방식 혹은 async/await 방식중에 선택해서 사용해주세요.

2022-08-05 03:02 UTC, lordmyshepherd commented on teamB/sockwon/app.js
> +})
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-06 12:53 UTC, sockwon commented
컨플릭트 해결을 먼저 해야 하는데 깜빡하고 push 를 했습니다. 이럴 때는 어떻게 컨플릭트를 해결해야 할지 잘 모르겠습니다.

2022-08-08 01:41 UTC, kyeongraekim requested changes

2022-08-08 01:41 UTC, kyeongraekim commented on teamB/sockwon/db/migrations/20220804034337_create_likes_table.sql
> +)
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-08 07:36 UTC, kyeongraekim requested changes

2022-08-08 07:36 UTC, kyeongraekim commented on teamB/sockwon/app.js
>  dotenv.config() //환경변수의 조정. 아래에 있었다면 에러가 났을 것이다. 위치에 신경써야.
- 상용화될 목적으로 푸시하는 깃헙 내 코드에서 코드 기능에 불필요한 주석문은 삭제해주세요!~

2022-08-08 07:36 UTC, kyeongraekim commented on teamB/sockwon/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- 올라와서는 안될 개인 로컬환경 내 관리되는 schema.sql 파일이 올라와있네요! 해당 내용 깃이그노어에 추가해주시고 또한 깃헙상에서 삭제해주세요!~

2022-08-08 07:36 UTC, kyeongraekim commented on teamB/sockwon/app.js
> +        ` //update 는 SET title="${title}", content="${content}" 처럼 따옴표를 꼭 넣어줘야 한다.
이곳도 불필요한 주석이 보이네요!

2022-08-08 07:36 UTC, kyeongraekim commented on teamB/sockwon/db/migrations/20220804034337_create_likes_table.sql
> +    post_id INT NOT NULL
유저나 게시글이 삭제되었음에도 사라지지 않는 db 내 좋아요 이력은 데이터베이스 자원의 불필요한 사용으로 간주될 수 있습니다.

따라서 On Delete Cascade에 대한 내용을 한 번 살펴보시고 parent table의 데이터가 사라졌을 때 child table에서 이어지는 추후 행동을 어떻게 의도하실지 다시 한 번 고민해보세요~

2022-08-09 01:39 UTC, lordmyshepherd commented
석원님! node_modules 폴더까지 같이 올리셔서 file change에 보면 5,000개가 넘는 파일이 올라와 있습니다!
node_modules/ 폴더는 github에 올라오지 않도록 .gitignore에 추가해주세요.

추가로, .gitignore에 등록했지만 그대로 github에 올라오는 경우는 아래 가이드를 참고해주세요.
- .gitignore에 등록하기 전에 한번이라도 git으로 관리해버린 파일들은(add, commit 등) 계속해서 git에 의해서 추적이 됩니다.
- 이를 없애기 위해서는 git의 기존 캐쉬를 삭제해줘야합니다.
- 아래의 명령어를 통해 캐쉬 삭제해주시고 git으로 추적 안되는 것 확인해주세요
- `git rm --cached 파일이름`
- 리모트의 git cache 삭제 후에는 반드시 리모트와 동기화 해줘야 합니다.
- `git add .`
- `git commit -m “커밋메시지”`
- `git push origin 브랜치이름`

2022-08-10 08:44 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-08-10 08:44 UTC, merged