[정재하 - teamA] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #89
Opened 2022-08-05 00:52 UTC by JeongJaeHa

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Express 초기 환경 세팅 및 westagram 기본 동작기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- **Express Setting** : Express 사용을 위한 morgan, cors, dotenv, Express, nodemon Install 및 기본 세팅 진행
- **회원가입 기능** : 유저 id, password, name, age 입력시 db users 테이블에 저장 및 상태코드 200, userCreated message 응답
- **게시글 등록 기능** : 유저 번호, 게시글 제목, 게시글 내용 작성하여 전송 시 posts 테이블 저장 및 상태코드 200 반환, postCreated message  응답
- **전체 게시글 조회** : 전체 작성된 글을 조회하여 JSON 형태로 전송
- **사용자 별 게시글 조회** : 유저 번호 입력시 해당 유저가 작성한 게시글을 조회하여 사용자의 이름, id, 게시글 목록을 JSON 형태로 전송,
- **게시글 수정 기능** : 게시글 번호, 유저 번호, 수정할 게시글 내용을 받아 posts 테이블을 조회하여 해당 게시글을 수정
- **게시글 삭제 기능** : 삭제할 게시글 번호 입력 시 해당 게시글 삭제
- ** 좋아요 기능** : 좋아요 누를 게시글 번호 입력 시 해당 게시글의 likes 컬럼 값이 1 증가.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 01:35 UTC, kyeongraekim requested changes

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +const { DataSource, SimpleConsoleLogger } = require('typeorm');
- simpleConsoleLogger는 아래 코드에서 보니 사용하지 않는 내용으로 보이네요! 사용하지 않는 코드는 늘 삭제해주시는 습관을 길러주세요. 
- 이외에 배포를 목적으로 깃헙 Main에 올리는 코드에서 log 기능을 담은 코드 푸시는 삼가주셔야 합니다.

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
>        res.status(200).json({ message: 'userCreated'})
user가 생성되었을 때의 http 상태코드는 200 이 아닌 다른 내용을 작성해주셔야 할것 같네요! 한 번 고민해주시고 반영해주세요!

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +      users_no,
users_no 와 같은 모호한 컬럼 테이블 명보다 user_id와 같은, user의 pk값을 명시하는, 정확한 rdbms 컨벤션에 맞는 컬럼명을 사용해주세요~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +      res.status(200).json({ message: 'postCreated'})
이곳 상태코드도 한 번 살펴주세요~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +app.get('/posts/viewAll', async (req, res) => {
endpoint에서의 대문자 사용은 지양하는 편입니다. 의미 구분을 위한 띄어쓰기 표현은 '-' 하이픈으로 대체해주세요~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +app.patch('/postEdit', async(req, res) => {
이곳 엔드포인트 대문자 사용도 고민해주세요. patch 라는 메소드에 이미 수정의 의미가 기능적으로 내포되어있기 때문에 Edit이라는 표현은 생략해주셔도 됩니다~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +      `UPDATE posts SET post = ? WHERE posts.no = ${post_no} AND posts.users_no = ${users_no}
이 부분도 다른 sql 문처럼 가독성 확보를 위해 line breaking을 진행해주세요~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +        res.status(200).json( {data :rows} )
결국 get 조회가 아닌 수정 patch에 대한 응답이니 클라이언트를 위해서, 리턴 메세지에 올바른 수정이 반영되었다는 메세지도 함께 전달해주면 좋을 것 같네요!~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +  res.status(204).json({ message: 'postingDeleted' })
204 code를 사용했을 때의 message 반환여부를 확인해보셨나요? postingDeleted라는 메세지가 성공적인 삭제 통신 이후에 나오는지 통신시험을 한 번 해보고 아래 코멘트로 남겨주세요!~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +  const { post_no } = req.paramsgit;
뒤에 붙은 git은 혹시 오타이실까요? 만일 그렇다면 상용화될 목적으로 푸시될 깃헙상 코드에는 오타가 절대 존재해서는 안됩니다! Syntax오류 등 잘 돌아가는 서버를 다운 시킬 가능성이 있으니 다음부터 유의하여 꼼꼼이 살피고 푸시해주세요!~

2022-08-05 01:35 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +  )
현재 로직은 post의 좋아요를 누른 횟수만 이력관리가 되고, 실제 어떤 유저와 그 좋아요가 매칭되는지 파악이 불가능 합니다. 유저의 좋아요, 좋아요 해지를 위해서는 user와의 연계성이 확보가 되어야 하는데 한 번 새롭게 모델링 로직을 고민해보세요!~

2022-08-05 02:09 UTC, kyeongraekim requested changes

2022-08-05 02:09 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +      title AS posting FROM posts
각각의 alias name이 기존 데이터 속성과 불일치한다는 생각이 드네요!~ AS 문 이후에 적절한 naming으로 다시 변경해주세요~

2022-08-05 02:22 UTC, kyeongraekim requested changes

2022-08-05 02:22 UTC, kyeongraekim commented on teamA/jeongjaeha/app.js
> +
해당 부분을 SQL 선에서도 해결을 할 수 있어보이네요~ 다음의 JSON array 관련 링크를 한 번 살펴보고 적용 여부를 판단해보세요!~
https://docs.microsoft.com/en-us/archive/blogs/sqlserverstorageengine/returning-child-rows-formatted-as-json-in-sql-server-queries

2022-08-06 11:00 UTC, JeongJaeHa commented on teamA/jeongjaeha/app.js
> +
해당 링크의 내용은 MsSQL로 현재 MySQL을 사용중인 이번 CRUD API 프로젝트에는 적용이 어렵다 판단됩니다.
JSON_ARRAYAGG, JSON_OBJECT 사용하여 MsSQL의 FOR JSON PATH 와 비슷한 결과 값 도출이 가능합니다.

2022-08-06 11:03 UTC, JeongJaeHa commented on teamA/jeongjaeha/app.js
> +  res.status(204).json({ message: 'postingDeleted' })
메세지는 출력되지 않습니다.

2022-08-08 01:44 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-08 01:44 UTC, merged