Feature/sign up seongmin
wecode-bootcamp-korea/36-backend-westagram pull request #9
Opened 2022-08-02 03:39 UTC by Seongmin-Gil

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원 정보를 받은 후 Database users 테이블에 데이터 저장
- 성공시 201 반환
![스크린샷 2022-08-02 오후 12 29 06](https://user-images.githubusercontent.com/103938821/182286597-1820634a-371b-4dd2-b215-e2036a563666.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 멘토님 리뷰 후 merge 없이 계속 진행하여도 괜찮은지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-03 02:23 UTC, kyeongraekim requested changes

2022-08-03 02:23 UTC, kyeongraekim commented on teamB/seongmin/westagram/.env.sample
> +DATABASE_URL="postgres://username:password@127.0.0.1:5432/database_name?sslmode=disable"
database url 내용에 postgres의 내용(RDBMS 명칭 및 Port 번호) 도 무언가 환경변수 샘플내용으로 관리하기에는 누군가에게 악용할 수 있을만한 큰 힌트가 될 수 있겠네요!~ 해당내용을 최소한으로 줄여보세요~

그리고 위코드에서는 기본적으로 Mysql을 사용하여 커리큘럼을 진행하고 있습니다. postgres 말고 mysql사용을 권장드립니다.

2022-08-03 02:23 UTC, kyeongraekim commented on teamB/seongmin/westagram/.gitignore
> +node_modules/
db 폴더내에 migrations 폴더는 깃헙에 올려서 다른 개발자들과 함께 확인하며 관리해야하는 목적이 있습니다. 다만 스키마 파일은 개별 로컬 환경에 따라 내부 상세 내용들이 언제든 변경될 수 있으니 아래의 내용을 초기환경 세팅시 사전에 추가해주세요!~ 
추가로 vscode 관련 불필요한 파일들이 올라오지 않게 vscode내용도 추가해주세요~

```
db/schema.sql
.vscode

2022-08-03 02:23 UTC, kyeongraekim commented on teamB/seongmin/westagram/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
이미 깃헙에 올라와버린 스키마.sql은 깃 캐시 삭제이후에 다시 애드 커밋 후 푸시하여서 깃헙상에서 schema.sql이 노출되지 않게 설정해주세요~

2022-08-03 02:23 UTC, kyeongraekim commented on teamB/seongmin/westagram/app.js
> +    SELECT u.id, u.name, u.email, u.profile_image, u.created_at FROM users u
해당 내용도 가독성 증가를 위해 아래와 같이 line breaking을 해주세요!~

2022-08-03 02:23 UTC, kyeongraekim commented on teamB/seongmin/westagram/app.js
> +app.post('/signUp', async(req, res) => {
RESTful 한 엔드포인트 설정에 맞게 users/signup 정도로 내가원하는 리소스의 상위 분기를 먼저 users로 실행해주세요!~

2022-08-03 04:35 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/.env.sample
> +DATABASE_URL="postgres://username:password@127.0.0.1:5432/database_name?sslmode=disable"
리뷰사항 반영하여 수정하였습니다.

2022-08-03 04:35 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/.gitignore
> +node_modules/
리뷰사항 반영하여 수정하였습니다.

2022-08-03 04:35 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
리뷰사항 반영하여 수정하였습니다.

2022-08-03 04:35 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/app.js
> +    SELECT u.id, u.name, u.email, u.profile_image, u.created_at FROM users u
리뷰사항 반영하여 수정하였습니다.

2022-08-03 04:35 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/app.js
> +app.post('/signUp', async(req, res) => {
리뷰사항 반영하여 수정하였습니다.

2022-08-03 05:05 UTC, kyeongraekim requested changes

2022-08-03 05:05 UTC, kyeongraekim commented on teamB/seongmin/westagram/app.js
> +//모든 사용자 조회
코드독해로 파악가능한 주석 설명문은 제거하는편 입니다~ 삭제를 고민해보세요~

2022-08-03 08:11 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/app.js
> +//모든 사용자 조회
주석 수정하여 반영하였습니다.

2022-08-04 01:19 UTC, kyeongraekim requested changes

2022-08-04 01:19 UTC, kyeongraekim commented on teamB/seongmin/westagram/app.js
> +app.post('/users/signUp', async(req, res) => {
RESTful 한 엔드포인드 디자인에서는 대문자 사용을 지양합니다. signup 혹은 sign-up 정도로 수정해주세요~

2022-08-04 01:19 UTC, kyeongraekim commented on teamB/seongmin/westagram/db/migrations/20220802004532_create_users.sql
> +    PRIMARY KEY (`id`)
PRIMARY KEY 선언만 10번에서는 간단히 적혀져있기 때문에, 개인적인 생각으로는 id 가 직접 명시되어있는 3번 라인에서 해주는게 더 가독성이 좋아보일 것 같네요!~ 만일 추후에 Primary Key를 위한 별도 설정을 의도하신거라면 10번에서 부터 확장성을 위해 현재 모습처럼 놔두어도 좋을 것 같네요!~

2022-08-04 01:19 UTC, kyeongraekim commented on teamB/seongmin/westagram/db/migrations/20220802004731_create_likes.sql
> +    CONSTRAINT `likes_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`)
foreign key constraint의 기능을 한 번 살펴보신 후에, 좋아요 이력관리를 하는 likes 테이블에서 post의 삭제와 관련지어서 foreign key constraint의 사용 필요성 여부를 한 번 판단해보세요!~

2022-08-04 01:19 UTC, kyeongraekim commented on teamB/seongmin/westagram/app.js
> +app.post('/users/signUp', async(req, res) => {
restful 한 엔드포인트 디자인 방식으로는 url에서 대문자 사용을 지양합니다. sign-up 정도로 띄어쓰기가 필요하면 하이픈을 이용해주세요~

2022-08-04 02:05 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/app.js
> +app.post('/users/signUp', async(req, res) => {
url 수정완료하였습니다.

2022-08-04 02:05 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/db/migrations/20220802004532_create_users.sql
> +    PRIMARY KEY (`id`)
primary key 위치를 수정하였습니다.

2022-08-04 02:06 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/db/migrations/20220802004731_create_likes.sql
> +    CONSTRAINT `likes_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`)
likes 테이블과 fk로 연결되어 posts  테이블 데이터 삭제 시 오류가 발생하여 likes와 posts 테이블 간의 fk 연결을 하지 않는 것으로 수정하였습니다.

2022-08-04 02:07 UTC, Seongmin-Gil commented on teamB/seongmin/westagram/app.js
> +app.post('/users/signUp', async(req, res) => {
수정완료하였습니다.

2022-08-04 02:56 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-04 02:56 UTC, merged