[박근우-teamB] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #90
Opened 2022-08-05 01:20 UTC by parklaus1078

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Express API CRUD 전체 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Express 초기 환경 세팅
- 유저 회원가입
- 게시글 등록하기
- 전체 게시글 조회하기
- 유저의 게시글 조회하기
- 게시글 수정하기
- 게시글 삭제하기
- 좋아요 누르기

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 02:27 UTC, kyeongraekim commented
근우님 node_modules 제거한 후 재푸시 해주세요~ 현재 불필요하게 5000개가 넘는 파일이 함께 올라와있네요.

2022-08-05 02:53 UTC, kyeongraekim requested changes

2022-08-05 02:53 UTC, kyeongraekim commented on .env
> +PORT = 4058
현재 환경변수 파일 자체가 올라와있네요. 해당 내용 깃 헙상에 노출되지 않게 설정해주세요. 환경변수 관련 업로드되어야할 파일은 env.sample 파일입니다. 깃 캐시 삭제 이후에 새롭게 업로드해주셔야 합니다.

2022-08-05 02:53 UTC, kyeongraekim commented on app.js
> +// health check
코드 독해로 충분히 파악가능한 주석문은 모두 삭제해주세요.

2022-08-05 02:53 UTC, kyeongraekim commented on app.js
> +    ) VALUES (?, ?, ?, ?, ?);`, [name, gender, birth, contact, mbti]);
뒤에 붙는 내용은 line breaking이 있어야 더 가독성이 확보 될 것 같네요!

2022-08-05 02:53 UTC, kyeongraekim commented on app.js
> +      *
웹서비스에서상용화될 코드에서 *의 사용은 꼭 필요한 경우가 아니면 지양해주셔야 합니다. 제 3자의 개발자들에게 읽힐 시간이 더 많을 코드라는 생각으로 내가 의도한 데이터 명을 최대한 명시해주세요~

2022-08-05 02:53 UTC, kyeongraekim commented on app.js
> +
현재 로직은 post의 좋아요를 누른 횟수만 이력관리가 되고, 실제 어떤 유저와 그 좋아요가 매칭되는지 파악이 불가능 합니다. 유저의 좋아요, 좋아요 해지를 위해서는 user와의 연계성이 확보가 되어야 하는데 한 번 새롭게 모델링 로직을 고민해보세요!~

2022-08-05 02:53 UTC, kyeongraekim commented on db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
해당 schmea.sql 파일은 개인 로컬 환경에 따라 경우의 수가 달라짐으로 다른이와 공유할 목적의 깃헙상에는 푸시해주시면 안됩니다. .gitignore관리 내용과 그 방법에 대해서 다시 한번 주도면밀하게 살펴주세요.

2022-08-05 02:53 UTC, kyeongraekim commented on app.js
> +  res.status(202).json({message: "postingDeleted"});
- 삭제 성공 메세지에 대한 http method는 200 혹은 204가 권장 됩니다~ 
- 만일 비동기 처리에 대한 내용을 고려하여 202를 선정해주셨다면 리턴 메세지가 postingDeleted외에 다른 내용으로 수정 되어야 할 것 입니다.
- 미들웨어로서의 사용을 하지 않는 next문은 현재 코드에서 삭제 해두 무방해보이네요!

2022-08-05 03:01 UTC, parklaus1078 commented on app.js
> +// health check
단순 질문입니다. 아래 코멘트에서 제 3자의 개발자들에게 읽힐 시간이 더 많을 코드라고 가정하고 작업을 진행하라고 말씀하셨습니다. 그렇다면 각 코드가 어떤 역할을 하는지 짧게 서술하는 주석문이 있는 편이 더 가독성을 높이지 않을까요?

2022-08-05 07:54 UTC, kyeongraekim requested changes

2022-08-05 07:54 UTC, kyeongraekim commented on app.js
> +   res.status(202).json({message: 'postCreated'});
- 게시글 생성 성공에 대한 메세지 전달을 위해서 201 상태코드도 맞추어 설정해주세요~

2022-08-05 07:54 UTC, kyeongraekim commented on app.js
> +  res.status(20).json({message: "postingDeleted"});
상태코드에 오타가 보이네요~

2022-08-05 07:54 UTC, kyeongraekim commented on app.js
> +});
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.

- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.

```
// callback 방식의 비동기처리
app.get("/posts", (req, res) => {
    myDataSource.query(`SELECT * FROM users`,
      // 비동기 처리 이후에 실행되는 callback
      (err, data) => {res.status(200).json({ data: data })}
    );
});

// async와 await 방식의 비동기처리
app.get("/posts", async(req, res) => {
  const users = await myDataSource.query(`SELECT * FROM users`);
  
  res.status(200).json({ data : users})
});
```

- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
https://www.youtube.com/watch?v=aoQSOZfz3vQ

2022-08-05 10:00 UTC, kyeongraekim requested changes

2022-08-05 10:00 UTC, kyeongraekim commented on db/migrations/20220803025744_posts.sql
> +	post_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
- posts 테이블에 있는 pk값을 보는 id 값이기 때문에 post_is는 verbose 해보일 수 있습니다. 추가로 다른 테이블이 해당 post 테이블을 바라보는 외래키로서의 오해 가능성이 있습니다.

2022-08-05 10:00 UTC, kyeongraekim commented on db/migrations/20220805035859_likes.sql
> +	like_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
- 이 곳도 위 내용과 마찬가지입니다. like_id를 id로 수정해주세요!

2022-08-08 02:09 UTC, kyeongraekim commented
- 현재 수많은 다른 사람들의 파일과 conflict가 나고 있습니다. 아마 작업하시면서 다른 사람들의 작업물도 건드신 것 같아 보이네요! 
- 다시 과거 commit 기록으로 돌아가서 내가 관리하고 있는 파일만 add commit 하고 다시 푸시해주는 수정이 필요할 것 으로 보입니다.

2022-08-08 06:53 UTC, closed without merging