[백민석 teamB] Assignment Api CRUD 전체 구현하기
wecode-bootcamp-korea/36-backend-westagram pull request #91
Opened 2022-08-05 01:26 UTC by sk8ilar

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

유저 회원가입 -확인완료
게시물 등록하기 - 확인완료
전체 게시글 조회 - 확인완료
유저별 게시글 조회 - 확인완료
게시글 수정 - 확인완료
게시글 삭제 - 확인완료
게시물 좋아요 -확인완료

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
들여쓰기에 관련된 부분 수정했고 추가로 가독성 안좋은 부분에 관해서 피드백 받고 싶습니다.!	 

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 03:17 UTC, lordmyshepherd requested changes

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +})
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +    await myDataSource.query(
변수 선언부와 함수 호출 사이에는 한 칸 띄워주세요-!

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +})
여기도 마찬가지로 한 칸씩 띄워주세요.

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +})})
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +            where user_id = ${receiveId}`,
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    // SELECT, FROM과 같은 키워드는 대문자료 표기해 주세요.
    
    await database.query(`
    		SELECT 
    			users.id,
    			users.name,
    			posts.id,
    			posts.title,
    			posts.content
    		FROM posts
    		JOIN users ON users.id = posts.user_id
    		WHERE posts.id = ..`
    );
    ```

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +    })
- callback 방식은 계속해서 중첩되는 구조에서는 가독성에 좋지 않습니다.
- 위에서 드린 피드백을 기준으로 async/await 방식으로 리펙토링 해주세요.

2022-08-05 03:17 UTC, lordmyshepherd commented on teamB/minseok/app.js
> +        `, [title, content]
- UPDATE SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
      UPDATE posts
      SET title = ?,
        description = ?
      WHERE id = ?`,
      [title, description, postId]
    );
    ```

2022-08-06 10:25 UTC, sk8ilar commented on teamB/minseok/app.js
> +    })
말씀하신 부분 전부 다 수정했습니다,

2022-08-08 01:46 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-08-08 01:47 UTC, merged