[이지현 teamA] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #93
Opened 2022-08-05 03:27 UTC by LeeJ1Hyun

## 수정 사항 간략한 한줄 요약
- 전체 게시글 조회, 유저의 게시글 조회, 게시글 수정, 게시글 삭제, 좋아요 누르기 기능 구현 / DB likes 테이블 생성, 수정
		 
## 수정 사항들 자세한 내용
#### 전체 게시글 조회
- GET / 전체 게시글 조회 가능

![게시글 전체 조회](https://user-images.githubusercontent.com/100523786/182986928-72ac5a32-c859-4b53-b960-705ceb9d35b9.png)

- 실패시 에러 반환
- 성공시 200 OK 반환

#### 유저의 게시글 조회
- GET / userId를 parameter로 받아 해당 유저의 게시글만 조회 가능

![유저 개인의 게시글 조회](https://user-images.githubusercontent.com/100523786/182987321-3750f561-3625-48cf-82e5-caa37d54a912.png)

- 실패시 에러 반환
- 성공시 200 OK 반환

#### 게시글 수정
- PATCH / postId를 parameter로 받아 해당 게시글 수정 가능

![유저 개인의 게시글 수정](https://user-images.githubusercontent.com/100523786/182987497-7317c84f-945d-4117-8de0-d1acc38eb8d0.png)

- 수정 후 바로 결과를 확인하기 위하여 SELECT문을 사용하여 같은 postId의 게시글을 바로 터미널에 출력
- 실패시 에러 반환
- 성공시 200 OK 반환 (수정 결과이므로 201이 아닌 200 사용)

#### 게시글 삭제
- DELETE / postId를 parameter로 받아 해당 게시글 삭제 가능

![유저 개인의 게시글 삭제 204](https://user-images.githubusercontent.com/100523786/182987919-b81a2e8b-24a9-49ca-a7f7-8527507675ee.png)

![유저 개인의 게시글 삭제 메세지 200](https://user-images.githubusercontent.com/100523786/182987951-05beba89-4040-4422-838c-2b07174df20d.png)

- 204를 반환하는 경우 사용자에게 보여지는 페이지를 바꾸지 않고 리소스를 업데이트할 때 쓰이기 때문에 별다른 메세지가 반환되지 않으므로 200을 사용하여 삭제되었다는 메세지를 보이게 함
- 실패시 에러 반환
- 성공시 200 OK 반환

#### 좋아요 누르기 기능 구현
- POST / postId를 parameter로 받아 해당 게시글 좋아요 누르기 가능

![유저 개인의 게시글 좋아요](https://user-images.githubusercontent.com/100523786/182988425-b899132e-bf43-4895-a8e0-b7dac0a108e8.png)

- likes 테이블 생성(각각 posts, users 테이블의 id들을 fk로 갖는 post_id, user_id를 컬럼으로 사용)
- 실패시 에러 반환
- 성공시 201, likeCreated 반환

#### DB likes 테이블 생성, 수정
- likes 테이블 생성
- posts 테이블 user_id, content 컬럼 NULL 허용 => NOT NULL 수정
- likes 테이블 user_id, post_id 컬럼 NULL 허용 => NOT NULL 수정

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 04:54 UTC, kyeongraekim requested changes

2022-08-05 04:54 UTC, kyeongraekim commented on teamA/jihyun/app.js
> +app.get("/posts/list/userId=:userId", async(req, res, next) => {
- RESTful 한 엔드포인트 설계법으로, 대문자 사용을 지양하는 것, 띄어쓰기가 필요한 곳은 '-' 하이픈을 이용하는 일종의 약속이 있습니다.  
- 그리고 userID=:userID 에서 앞에 userID=는 삭제해주셔도 될 것 같은데 그 이유를 한 번 고민해보세요! 

- 미들웨어로서 사용하지 않는 함수에서는 next 매개변수를 생략해주셔도 됩니다~

2022-08-05 04:54 UTC, kyeongraekim commented on teamA/jihyun/app.js
> +});
해당 부분을 SQL 선에서도 해결을 할 수 있어보이네요~ 다음의 JSON array 관련 링크를 한 번 살펴보고 적용 여부를 판단해보세요!~
https://docs.microsoft.com/en-us/archive/blogs/sqlserverstorageengine/returning-child-rows-formatted-as-json-in-sql-server-queries

2022-08-05 04:54 UTC, kyeongraekim commented on teamA/jihyun/app.js
> +      res.status(200).json({ "data" : rows });
patch 업데이트에 대한 리턴 상태코드이니 200이 아닌 다른 옵션은 없는지 한 번 고민해보세요!~

2022-08-05 04:54 UTC, kyeongraekim commented on teamA/jihyun/app.js
> +  res.status(200).json({ message : "postingDeleted" });
- 204 code를 사용했을 때의 message 반환여부를 혹시 확인해보셨나요? postingDeleted라는 메세지가 성공적인 삭제 통신 이후에 나오는지 통신시험을 한 번 해보고 아래 코멘트로 남겨주세요!~

2022-08-05 04:54 UTC, kyeongraekim commented on teamA/jihyun/db/migrations/20220805011220_create_like_table.sql
> +    CONSTRAINT likes_user_id FOREIGN KEY (user_id) REFERENCES users(id),
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.

- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.

- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
```
+----+---------+---------+---------------------+
| id | user_id | post_id | created_at |
+----+---------+---------+---------------------+
| 1 | 1 | 3 | 2022-07-16 14:18:26 |
| 2 | 1 | 3 | 2022-07-16 14:18:26 |
| 3 | 1 | 3 | 2022-07-16 14:18:26 |
| 4 | 1 | 3 | 2022-07-16 14:18:26 |
| 5 | 1 | 3 | 2022-07-16 14:18:47 |
| 6 | 1 | 3 | 2022-07-16 14:18:47 |
+----+---------+---------+---------------------+
```
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-08-05 07:02 UTC, LeeJ1Hyun commented on teamA/jihyun/db/migrations/20220805011220_create_like_table.sql
> +    CONSTRAINT likes_user_id FOREIGN KEY (user_id) REFERENCES users(id),
https://github.com/wecode-bootcamp-korea/36-backend-westagram/pull/93/files#diff-b326b67aadb215b1eea2c18724c8f1b672dfbe5c015def51deb1e3d56d1e027e

두번째 커밋에 반영되어 있습니다. 말씀하신 게 이 부분 맞을까요?

2022-08-06 06:44 UTC, LeeJ1Hyun commented on teamA/jihyun/app.js
> +app.get("/posts/list/userId=:userId", async(req, res, next) => {
띄어쓰기가 필요한 곳은 하이픈('-')으로 변경하였고, userId= 를 /users/로 수정하였습니다. 해당 app.js에서는 미들웨어로 사용하는 함수가 없기 때문에 next 매개변수를 모두 삭제하였습니다. 꼼꼼한 코드리뷰 감사드립니다!

2022-08-06 06:44 UTC, LeeJ1Hyun commented on teamA/jihyun/app.js
> +      res.status(200).json({ "data" : rows });
204 코드로 수정하였습니다. 200 상태코드를 설정한 이유는 update 후에 select 로 결과도 함께 보여주기 때문에 상태코드는 200으로 반환해야겠다고 생각했습니다. https://developer.mozilla.org/ko/docs/Web/HTTP/Status/204 해당 링크에서는 새로 결과를 보여주는 경우 200코드를 추천하는데 실제 결과를 사용자에게 보여주는 것이 아니라 터미널에서 개발자만 확인하는 것이므로 204코드를 쓰는 게 더 좋은 선택일까요?

2022-08-06 06:44 UTC, LeeJ1Hyun commented on teamA/jihyun/app.js
> +  res.status(200).json({ message : "postingDeleted" });
pr의 게시글 삭제 파트에 사진과 함께 200, 204 상태코드 결과를 비교해두었습니다. 왜 200코드를 선택하게 되었는지도 작성되어 있습니다!

2022-08-06 19:36 UTC, LeeJ1Hyun commented on teamA/jihyun/app.js
> +});
https://dev.mysql.com/worklog/task/?id=11574, https://dev.mysql.com/doc/refman/8.0/en/json-creation-functions.html 두 문서를 참고하여 
![쿼리](https://user-images.githubusercontent.com/100523786/183263702-25731aa6-e385-44ba-94d6-33acd6b9e99e.png)
위와 같은 쿼리문을 작성하여 
![user1](https://user-images.githubusercontent.com/100523786/183263719-3e649bca-b0fd-4cd6-8e91-7a470a0b7c32.png)
원하는 형태로 데이터를 출력할 수 있었습니다. 감사합니다~

2022-08-08 01:58 UTC, kyeongraekim approved these changes
LGTM!~ 새로운 브랜치에 layered pattern 적용해서 계속 이어서 올려주세요~

2022-08-08 01:58 UTC, merged