[정세한 teamA] Assignment: Express API CRUD 전체 기능
wecode-bootcamp-korea/36-backend-westagram pull request #96
Opened 2022-08-05 08:35 UTC by jungsae

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- GET, POST, PATCH, DELECT HTTP method들을 사용해서, 성공시 메세지나, 결과값을 보여줍니다.

## 기타 질문 및 특이 사항
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-05 10:23 UTC, kyeongraekim requested changes

2022-08-05 10:23 UTC, kyeongraekim commented on teamA/saehan/app.js
> +app.get('/viewAllPosts', async(req,res,next) => {
- http 메소드선택시 그 의미와 기능이 명시되기 떄문에, 엔드포인트 타겟 리소스에는 동사 형태의 영어 단어를 작성하지 않습니다. 
- 미들웨어로의 next() 메소드를 아래 별도로 적용하지 않는다면 매개변수로 받을 필요가 없을 것 같네요!~ 제거해주셔도 괜찮습니다.

2022-08-05 10:23 UTC, kyeongraekim commented on teamA/saehan/app.js
> +app.post('/like/:userId/:postId', async(req,res,next) => {
- 엔드포인트뒤에 like/1/1형식으로 숫자가 오게되면 리소스 내용의 의미가 불분명하게 전달이 되게 됩니다. RESTful 한 엔드포인트 설계법에는, 해당 URL을 봤을 때 그 의미와 기능파악이 한눈에 되어야만 합니다. 따라서 like/post/1/user/1  정도를 추천드리고, 해당 방법은 userId를 노출 시킬 수 있는 방법이니 ,

- 현재 선택해주신 post의 기능을 활용해 userId, postId를 바디에 담아서 보내도 될 것 같습니다.

2022-08-05 10:23 UTC, kyeongraekim commented on teamA/saehan/app.js
> +        );
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-08-06 17:13 UTC, jungsae commented on teamA/saehan/app.js
> +app.post('/like/:userId/:postId', async(req,res,next) => {
넵!

2022-08-06 17:14 UTC, jungsae commented on teamA/saehan/app.js
> +app.get('/viewAllPosts', async(req,res,next) => {
넵!

2022-08-08 02:02 UTC, kyeongraekim approved these changes
코드는 LGTM 이지만 컨플릭트가 났네요! 로컬에서 컨플릭트 해결해서 재푸시해주세요!

2022-08-08 07:09 UTC, kyeongraekim requested changes
컨플릭트 해결중..

2022-08-08 07:27 UTC, kyeongraekim approved these changes
LGTM!~ 이어서 새로운 브랜치에서 Layered pattern 반영 진행해주세요!~

2022-08-08 07:28 UTC, merged